-- Oracle DDL — auto_trade_* (자동매매 엔진, 5종목 슬롯 + 드라이런/서킷브레이커).
-- 설계: docs/design/808-auto-trade-engine/README.md §6
-- 멱등 실행: 이미 있으면(ORA-00955) 무시.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE auto_trade_candidate (
      id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol                VARCHAR2(20)  NOT NULL,
      market                VARCHAR2(10)  NOT NULL,
      valuation_note        VARCHAR2(500),
      valuation_checked_at  TIMESTAMP,
      active                NUMBER(1)     DEFAULT 1 NOT NULL,
      created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE auto_trade_position (
      id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol            VARCHAR2(20)  NOT NULL,
      market            VARCHAR2(10)  NOT NULL,
      status            VARCHAR2(20)  NOT NULL,
      entry_price       NUMBER        NOT NULL,
      entry_qty         NUMBER        NOT NULL,
      entry_at          TIMESTAMP     NOT NULL,
      peak_price        NUMBER        NOT NULL,
      budget_allocated  NUMBER        NOT NULL,
      exit_price        NUMBER,
      exit_reason       VARCHAR2(30),
      exit_at           TIMESTAMP,
      dry_run           NUMBER(1)     DEFAULT 1 NOT NULL,
      created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE auto_trade_state (
      id                          NUMBER PRIMARY KEY,
      total_budget                NUMBER        NOT NULL,
      per_symbol_budget           NUMBER        NOT NULL,
      dry_run                     NUMBER(1)     DEFAULT 1 NOT NULL,
      circuit_breaker_tripped     NUMBER(1)     DEFAULT 0 NOT NULL,
      circuit_breaker_tripped_at  TIMESTAMP,
      updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 싱글턴 초기 행(id=1) — 없을 때만 삽입. 예산 500만원/5종목=100만원, dryRun 기본 ON.
BEGIN
  INSERT INTO auto_trade_state (id, total_budget, per_symbol_budget, dry_run, circuit_breaker_tripped)
  VALUES (1, 5000000, 1000000, 1, 0);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1 THEN RAISE; END IF;  -- ORA-00001: unique constraint violated(이미 존재)
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE auto_trade_order_log (
      id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol            VARCHAR2(20)  NOT NULL,
      side              VARCHAR2(10)  NOT NULL,
      reason            VARCHAR2(30)  NOT NULL,
      dry_run           NUMBER(1)     NOT NULL,
      requested_qty     NUMBER,
      requested_price   NUMBER,
      toss_order_id     VARCHAR2(200),
      success           NUMBER(1)     DEFAULT 1 NOT NULL,
      message           VARCHAR2(500),
      created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2026-10-01 버그 수정: 실제 Toss 주문체결 시 orderId가 86자까지 나오는데 컬럼이 50자라
-- ORA-12899 발생 → saveLog()가 실패해서 "실제로 체결된 매수"가 기록도 안 되고, 그래서
-- positionMapper.insert()까지 도달 못 해 포지션도 안 남음(이미 보유 중인지 체크가 안 돼
-- 같은 종목을 틱마다 반복 매수하는 사고로 이어짐, 012330 5회 중복매수 실사례). 기존 테이블도 넓힘.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE auto_trade_order_log MODIFY (toss_order_id VARCHAR2(200))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -904 THEN RAISE; END IF; -- 컬럼 없음(아직 테이블 자체가 새로 생성된 경우) 무시
END;
/
