-- Oracle DDL — 수동 보유 포트폴리오 (#430). 멱등.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE holding (
      id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol     VARCHAR2(6)  NOT NULL,
      buy_at     TIMESTAMP    NOT NULL,
      buy_price  NUMBER       NOT NULL,
      quantity   NUMBER,
      stop_pct   NUMBER DEFAULT 8,
      memo       VARCHAR2(200),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
-- #433 거래원장: 매수/매도 구분. 기존 행은 BUY 로 마이그레이션. 멱등.
BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE holding ADD (side VARCHAR2(4) DEFAULT 'BUY' NOT NULL)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;  -- -1430: 컬럼 이미 존재
END;
/
