-- Oracle DDL — range_trade_* (#818 레인지(박스권) 스윙매매, 2번째 자동매매 트랙).
-- 설계: docs/design/818-range-trade-swing/README.md §6
-- #808 auto_trade_* 와 완전히 분리된 테이블 — 예산/슬롯/서킷브레이커가 서로 영향 없음(README §11).
-- range_trade_candidate 는 만들지 않는다(매일 유니버스 전체 스캔 방식, README §6).
-- 멱등 실행: 이미 있으면(ORA-00955) 무시.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE range_trade_position (
      id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol               VARCHAR2(20)  NOT NULL,
      market               VARCHAR2(10)  NOT NULL,
      status               VARCHAR2(20)  NOT NULL,
      entry_price          NUMBER        NOT NULL,
      entry_qty            NUMBER        NOT NULL,
      entry_at             TIMESTAMP     NOT NULL,
      range_low_at_entry   NUMBER        NOT NULL,
      range_high_at_entry  NUMBER        NOT NULL,
      budget_allocated     NUMBER        NOT NULL,
      exit_price           NUMBER,
      exit_reason          VARCHAR2(30),
      exit_at              TIMESTAMP,
      dry_run              NUMBER(1)     DEFAULT 1 NOT NULL,
      created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE range_trade_state (
      id                          NUMBER PRIMARY KEY,
      total_budget                NUMBER        NOT NULL,
      max_symbols                 NUMBER        NOT NULL,
      per_symbol_budget           NUMBER        NOT NULL,
      dry_run                     NUMBER(1)     DEFAULT 1 NOT NULL,
      circuit_breaker_tripped     NUMBER(1)     DEFAULT 0 NOT NULL,
      circuit_breaker_tripped_at  TIMESTAMP,
      updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 싱글턴 초기 행(id=1) — 없을 때만 삽입. 예산 100만원/2슬롯=50만원(README §12 확정), dryRun 기본 ON.
BEGIN
  INSERT INTO range_trade_state (id, total_budget, max_symbols, per_symbol_budget, dry_run, circuit_breaker_tripped)
  VALUES (1, 1000000, 2, 500000, 1, 0);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1 THEN RAISE; END IF;  -- ORA-00001: unique constraint violated(이미 존재)
END;
/

-- toss_order_id 는 처음부터 VARCHAR2(200) — 2026-10-01 #808 사고 교훈(실제 Toss orderId가 86자까지
-- 나오는데 컬럼이 50자라 ORA-12899 → 감사로그 INSERT 실패가 포지션 기록까지 막아 같은 종목을
-- 반복 매수한 사고, 012330 5회). 레인지 트랙은 같은 실수를 반복하지 않도록 넉넉히 잡고 시작.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE range_trade_order_log (
      id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol            VARCHAR2(20)  NOT NULL,
      side              VARCHAR2(10)  NOT NULL,
      reason            VARCHAR2(30)  NOT NULL,
      dry_run           NUMBER(1)     NOT NULL,
      requested_qty     NUMBER,
      requested_price   NUMBER,
      toss_order_id     VARCHAR2(200),
      success           NUMBER(1)     DEFAULT 1 NOT NULL,
      message           VARCHAR2(500),
      created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2026-10-07(#841) — #808과 동일한 수수료/세금 미기록 문제, 레인지 트랙도 같이 수정.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE range_trade_order_log ADD (commission NUMBER, tax NUMBER)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF; -- 이미 존재
END;
/

-- 2026-10-08(#849) — #808과 동일하게 SELL 로그에 진입가 저장.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE range_trade_order_log ADD (entry_price NUMBER)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF; -- 이미 존재
END;
/
