-- Oracle DDL — reentry_watch (추적손절 재진입 알림 감시 대상).
-- 설계: docs/design/reentry-alert/README.md §6
-- 멱등 실행: 이미 있으면(ORA-00955) 무시.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE reentry_watch (
      id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol             VARCHAR2(20)  NOT NULL,
      reference_price    NUMBER        NOT NULL,
      stage1_pct         NUMBER        DEFAULT 5  NOT NULL,
      stage2_pct         NUMBER        DEFAULT 10 NOT NULL,
      stage1_alerted_at  TIMESTAMP,
      stage2_alerted_at  TIMESTAMP,
      active             NUMBER(1)     DEFAULT 1  NOT NULL,
      created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;  -- ORA-00955: name is already used
END;
/
