-- Oracle DDL — 뉴스 S1-S5 분류 (#425). 멱등.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE stock_news (
      id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ext_id       VARCHAR2(64)  NOT NULL,
      title        VARCHAR2(500) NOT NULL,
      url          VARCHAR2(1000),
      source       VARCHAR2(60),
      published_at TIMESTAMP,
      fetched_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      status       VARCHAR2(12) DEFAULT 'RECEIVED' NOT NULL,  -- RECEIVED/ANALYZED/EXPIRED
      targets      VARCHAR2(400),   -- 005930,반도체,MARKET
      sentiment    VARCHAR2(400),   -- 005930:S5,반도체:S5,MARKET:S3
      rationale    VARCHAR2(2000),
      kind         VARCHAR2(12),    -- EVENT/SPECULATION
      model        VARCHAR2(60),
      expires_at   TIMESTAMP,
      CONSTRAINT uq_stock_news_ext UNIQUE (ext_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
-- #865 촉매 자격 판정용 사실 JSON. 기존 테이블에도 붙도록 ALTER(-1430 = 컬럼 이미 존재).
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE stock_news ADD (facts CLOB)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
-- #867 fetched_at 기본값을 UTC(SYSTIMESTAMP) → KST(CURRENT_TIMESTAMP) 로 교정.
-- SYSTIMESTAMP 는 DB 타임존(UTC), CURRENT_TIMESTAMP 는 세션 타임존(Asia/Seoul)이다.
-- 이 프로젝트의 다른 시각 컬럼은 전부 KST 라, 이 컬럼만 9시간 과거로 기록돼
-- findRecentEvents 의 실효 조회구간이 24시간이 아니라 15시간이었다.
-- MODIFY DEFAULT 는 같은 값으로 반복 실행해도 예외가 없다(멱등).
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE stock_news MODIFY (fetched_at DEFAULT CURRENT_TIMESTAMP)';
END;
/
