-- Oracle DDL — 뉴스 S1-S5 분류 (#425). 멱등.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE stock_news (
      id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ext_id       VARCHAR2(64)  NOT NULL,
      title        VARCHAR2(500) NOT NULL,
      url          VARCHAR2(1000),
      source       VARCHAR2(60),
      published_at TIMESTAMP,
      fetched_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      status       VARCHAR2(12) DEFAULT 'RECEIVED' NOT NULL,  -- RECEIVED/ANALYZED/EXPIRED
      targets      VARCHAR2(400),   -- 005930,반도체,MARKET
      sentiment    VARCHAR2(400),   -- 005930:S5,반도체:S5,MARKET:S3
      rationale    VARCHAR2(2000),
      kind         VARCHAR2(12),    -- EVENT/SPECULATION
      model        VARCHAR2(60),
      expires_at   TIMESTAMP,
      CONSTRAINT uq_stock_news_ext UNIQUE (ext_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
