-- Oracle DDL — watchlist (HikariCP + MyBatis 스모크).
-- 멱등 실행: 이미 있으면(ORA-00955) 무시. SQLcl/Database Actions 에서 실행하거나
-- OracleWatchlistIT 가 부팅 시 동일 DDL 을 멱등 적용한다.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE watchlist (
      id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol     VARCHAR2(20)  NOT NULL,
      memo       VARCHAR2(200),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;  -- ORA-00955: name is already used
END;
/
