package com.cloudhandson.tossstock.db;

import com.cloudhandson.tossstock.watchlist.Watchlist;
import com.cloudhandson.tossstock.watchlist.WatchlistMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 실제 Oracle Autonomous DB 통합 테스트 (HikariCP + MyBatis end-to-end).
 * ORACLE_PASSWORD 환경변수가 있을 때만 실행. 멱등 DDL(테이블 없으면 생성).
 * 실행: set -a; . ./.env; set +a; mvn -Dit.test=OracleWatchlistIT verify
 */
@SpringBootTest
@ActiveProfiles("oracle")
@EnabledIfEnvironmentVariable(named = "ORACLE_PASSWORD", matches = ".+")
class OracleWatchlistIT {

    private static final String DDL = """
            BEGIN
              EXECUTE IMMEDIATE 'CREATE TABLE watchlist (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                symbol VARCHAR2(20) NOT NULL,
                memo VARCHAR2(200),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)';
            EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """;

    @Autowired
    DataSource dataSource;

    @Autowired
    WatchlistMapper watchlistMapper;

    @BeforeEach
    void ensureTable() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute(DDL);
        }
    }

    @Test
    void hikari_connects_to_autonomous_db() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT 'OK' FROM dual")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString(1)).isEqualTo("OK");
            assertThat(c.getMetaData().getDatabaseProductName()).containsIgnoringCase("Oracle");
        }
    }

    @Test
    void mybatis_insert_and_read_roundtrip() {
        Watchlist w = new Watchlist();
        w.setSymbol("005930");
        w.setMemo("oracle-IT roundtrip");
        int inserted = watchlistMapper.insert(w);
        assertThat(inserted).isEqualTo(1);

        assertThat(watchlistMapper.findAll())
                .extracting(Watchlist::getSymbol)
                .contains("005930");
    }
}
