-- 테스트용 H2(MODE=Oracle) 스키마 — 실 Oracle DDL(db/watchlist.sql)과 동일 형태.
CREATE TABLE IF NOT EXISTS watchlist (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol     VARCHAR(20)  NOT NULL,
    memo       VARCHAR(200),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 시드: 삼성전자
INSERT INTO watchlist (symbol, memo) VALUES ('005930', '삼성전자 - seed');
